/**
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package br.com.sergio.apicliente.v1.controller;

import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.ResponseStatus;

import br.com.sergio.apicliente.v1.model.ApiRespostaErro;
import br.com.sergio.apicliente.v1.model.Cliente;
import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;

/**
 * Interface com a documentação para API de Clientes
 * 
 * @author Sérgio
 */
@Api(value = "clientes")
public interface ClientesApi {
	
	/**
	 * Endpoint para receber as atualizações dos dados da Campanha
	 * 
	 * @param dados {@link Cliente}
	 */
    @ApiOperation(value = "Cadastra cliente", notes = "", tags={ "clientes", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "Cliente cadastrado com sucesso", response = Cliente.class),
        @ApiResponse(code = 400, message = "Dados de entrada inválidos", response = ApiRespostaErro.class) })
    @RequestMapping(value = "/clientes",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    @ResponseBody
	@ResponseStatus(HttpStatus.CREATED)
    Cliente cadastraCliente(@ApiParam(value = "Dados do cliente", required=true ) Cliente dados);

}
